[package]
name = "skyfighterdataset"
version = "0.1.0"
edition = "2021"

[dependencies]
opencv = { version = "0.63", default-features = false, features = ["dnn", "clang-runtime"] }
image = "0.24"
tokio = { version = "1.0", features = ["full"] }
glob = "0.3"

[build-dependencies]
pkg-config = "0.3"